### ISSUE TITLE
hypotheses to test

### ISSUE THREAD

**Issue by dnkennedy** [ReproNim/simple_workflow-02#4]

**Comment by dnkennedy** [comment]
I couple of papers in the literature have been identified that provides some existing findings that we feel would be ripe for replication.  These papers, and their associated findings are:

1) Pietschnig et al. Meta-analysis of associations between human brain volume and intelligence differences: How strong  are they and what do they mean? Neurosci Biobehav Rev. 2015 Oct;57:411-32. 
[(https://www.ncbi.nlm.nih.gov/pubmed/26449760)]
[https://drive.google.com/open?id=1GRfusrXU3k4Ui5t1qW0l8KnF9hli6ELR]

"Our results showed significant positive associations of brain volume and IQ (r = .24, R2 = .06) that generalize over age (children vs. adults), IQ domain (full-scale, performance, and verbal IQ), and sex."

2) MacDonald PA, et al. Investigating the relation between striatal volume and IQ. Brain Imaging Behav. 2014 Mar;8(1):52-9.  
[https://link.springer.com/article/10.1007/s11682-013-9242-3]
[https://drive.google.com/open?id=10pBvBZ0DqUMMresFMPTu2xXSqiwupwsB]

"Correlations between the WASI-IQ and the left striatum, composed of the caudate nucleus and putamen, were significant. When these data were analyzed separately for male and female children, positive correlations were significant for the left striatum in male children only."

3) Ganjavi H, et al.  Negative associations between corpus callosum midsagittal area and IQ in a representative sample of healthy children and adolescents.  PLoS One. 2011;6(5):e19698. 
[https://drive.google.com/open?id=17vghZbNMumKJVkywQ_YJ1bOlAhlk5Exu]

"After correcting for total brain volume and age, a significant negative correlation was found between total CC midsagittal area and IQ (r = −0.147; p = 0.040). Post hoc analyses revealed a significant negative correlation in children (age<12) (r = −0.279; p = 0.004) but not in adolescents (age≥12) (r = −0.005; p = 0.962). Partitioning the subjects by gender revealed a negative correlation in males (r = −0.231; p = 0.034) but not in females (r = 0.083; p = 0.389)."

**Comment by dnkennedy** [comment]
In summary, I propose the following 'Final Hypotheses':

1. Total Brain Volume will positively correlate with IQ (in both sexes across the complete age range).

2. Left striatum volume (caudate + putamen) will positively correlate with IQ in the total (male + female) child (age < 20) group. 

2a. Left striatum volume (caudate + putamen) will positively correlate with IQ in the male children group.

2b. Left striatum volume (caudate + putamen) will not correlate with IQ in the female children group.

3. Total Corpus Callosum midsagittal area, after correcting for total brain volume, will negatively correlate with IQ.

3a. Total Corpus Callosum midsagittal area, after correcting for total brain volume, will negatively correlate with IQ in the young (age < 12) group.

3b. Total Corpus Callosum midsagittal area, after correcting for total brain volume, will not correlate with IQ in the adolescent (age > 12) group.

3c. Total Corpus Callosum midsagittal area, after correcting for total brain volume, will negatively correlate with IQ in the male (age < 12) group.

3d. Total Corpus Callosum midsagittal area, after correcting for total brain volume, will not correlate with IQ in the female (age < 12) group.

**Comment by dnkennedy** [comment]
Please comment on these hypotheses. If these are acceptable, they will be etched into stone (i.e. hypothesis registered with OSF).

**Comment by yarikoptic** [comment]
I wondered should we stay in "Anatomical" domain or expand into "Functional" altogether?  Amount of variability there is much larger (different "operationalized" designs), smaller sample sizes, but larger data arrays, more variance in methods, etc ....

**Comment by jbpoline** [comment]
Hey

I have not yet had the time to review in detail but just wanted to point to
a classic issue in the null hypothesis testing framework: we cannot test
for the "will not correlate" one(s) !

More soon ;)

Cheers

JB


On Feb 8, 2018 10:36 PM, "Yaroslav Halchenko" <notifications@github.com>
wrote:

I wondered should we stay in "Anatomical" domain or expand into
"Functional" altogether? Amount of variability there is much larger
(different "operationalized" designs), smaller sample sizes, but larger
data arrays, more variance in methods, etc ....

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ReproNim/simple_workflow-02/issues/4#issuecomment-364325828>,
or mute the thread

**Comment by dnkennedy** [comment]
Re: @yarikoptic question regarding 'anatomical' versus 'functional' domains. IMHO, precisely because functional is more complex, I'd like to attempt to see if we can 'solve' (or at least make progress on) the 'easier' topics. One could imaging a second paper, Simple2a, that then looks at the same questions regarding resting-state, etc.

**Comment by dnkennedy** [comment]
Re: @jbpoline observation about testing 'not correlated': Oops, sorry about that. So, we should rephrase to hypothesize to expect to see correlation, and then if we don't confirm that hypothesis, we'll report that as a confirmation of the literature we were attempting to replicate?

**Comment by jbpoline** [comment]
@dnkennedy  We can still do it - but have to go Bayesian !

**Comment by dnkennedy** [comment]
Hypotheses at: https://osf.io/yuv52
